#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "FILE_STRUCTURE_GRAPH.md"

SKIP_DIRS = {".git", "__pycache__", "build"}
SKIP_SUFFIXES = {
    ".aux",
    ".bbl",
    ".blg",
    ".dvi",
    ".fdb_latexmk",
    ".fls",
    ".log",
    ".out",
    ".pdf",
    ".synctex.gz",
    ".toc",
    ".xdv",
}
SKIP_NAMES = {"demo.synctex(busy)"}

NOTES = {
    ".latexmkrc": "latexmk XeLaTeX build configuration",
    "CWNUExam.cls": "main CWNU exam document class",
    "README.md": "project usage documentation",
    "template/demo.tex": "blank starter template",
}


def should_skip(path: Path) -> bool:
    parts = set(path.relative_to(ROOT).parts)
    if parts & SKIP_DIRS:
        return True
    if path.name in SKIP_NAMES:
        return True
    if any(path.name.endswith(suffix) for suffix in SKIP_SUFFIXES):
        return True
    return False


def visible_children(directory: Path) -> list[Path]:
    children = [child for child in directory.iterdir() if not should_skip(child)]
    return sorted(children, key=lambda child: (not child.is_dir(), child.name.lower()))


def render_tree(directory: Path, prefix: str = "") -> list[str]:
    lines: list[str] = []
    children = visible_children(directory)
    for index, child in enumerate(children):
        connector = "`-- " if index == len(children) - 1 else "|-- "
        rel = child.relative_to(ROOT).as_posix()
        note = f" - {NOTES[rel]}" if rel in NOTES else ""
        suffix = "/" if child.is_dir() else ""
        lines.append(f"{prefix}{connector}{child.name}{suffix}{note}")
        if child.is_dir():
            extension = "    " if index == len(children) - 1 else "|   "
            lines.extend(render_tree(child, prefix + extension))
    return lines


def main() -> None:
    body = "\n".join(render_tree(ROOT))
    OUTPUT.write_text(
        "# File Structure Graph\n\n"
        "Generated by `scripts/update_file_structure_graph.py`.\n\n"
        "```text\n"
        ".\n"
        f"{body}\n"
        "```\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
